sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t orchsik/docker-react-app:1 -f dockerfile.dev ./

script:
  - docker run -e CI=true orchsik/docker-react-app:1 npm run test -- --coverage

after_success:
  - echo "Test Success"
